Controllers films users
PetrutikSA/java-filmorate pull request #5
Opened 2024-05-25 21:02 UTC by PetrutikSA

Дополнительное задание сделал, валидацию полей указал с помощью аннотаций.
Но так как тесты написаны без использований тестовых механик Spring-а (я полагаю что мы это будем дальше изучать как корректно тестить Spring приложения, пока наставник рекомендовал просто протестить валидацию создавая самому объекты контроллеров), то данные аннотации в тестах не работали, пришлось указать отдельный метод для валидации filmValidationControl(Film film)  и userValidationControl(User user). 
Через Postman с приложенным ТЗ вариантом тестовых запросов работает даже если указанные выше методы закоммитить.

2024-05-26 18:56 UTC, afomkina requested changes

2024-05-26 18:56 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private void filmValidationControl(Film film) {
Этот метод не нужен, так как за валидацию отвечают аннотации Spring

2024-05-26 18:56 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private Integer getNextFilmId() {
Лучше использовать счетчик, как и в прошлом проекте

2024-05-26 18:56 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private void userValidationControl(User user) {
Метод нужно удалить, так как валидацией занимается спринг

2024-05-26 19:02 UTC, afomkina commented
Привет! Работа получилась отличной, она полностью соответствует ТЗ. Классно, что ты решил исследовать дополнительное задание и добавил валидацию с помощью Spring!

Я видела, что ты добавил методы для тестирования, пока мы еще не изучали тестирование спринга, однако отметила в комментариях, что данные методы стоит удалить. 

Оставляю на твое усмотрение, исправлять ли сейчас код или нет. Однако я бы порекомендовала попробовать переписать тесты сейчас и избавиться от дублирующих методов, потому что, оставляя это на потом, всегда можно об этом забыть.

Чтобы проверить валидацию без тестирования Spring, можно воспользоваться [валидатором](https://stackoverflow.com/questions/29069956/how-to-test-validation-annotations-of-a-class-using-junit).

2024-05-28 09:53 UTC, PetrutikSA commented
Переделал тесты с использованием валидатора, остальные замечания так же исправил.

2024-05-28 12:55 UTC, afomkina approved these changes

2024-05-28 13:33 UTC, merged