Add friends likes
PetrutikSA/java-filmorate pull request #6
Opened 2024-06-10 14:47 UTC by PetrutikSA

Задания в ТЗ сделал, тесты в Postman приложеные к ТЗ проходят.
Сервисы сделал тоже через интерфейсы по аналогии с классами Storage, чтобы изолировать их реализацию от контроллеров

2024-06-11 14:42 UTC, afomkina requested changes
Получилась отличная работа, она полностью соответсвует тз и выглядит очень структурировано и чисто. Оставила небольшой комментарий для саморазвития

2024-06-11 14:42 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/handler/ErrorHandler.java
> +        log.warn(String.format("Validation exception: %s", exception.getMessage()));
При логировании параметров, лучше использовать заполнитель(placeholder) {}, а не `String.format.`

Так код будет выглядеть более лаконично

2024-06-12 18:41 UTC, PetrutikSA commented
Исправил

2024-06-13 14:12 UTC, afomkina approved these changes

2024-06-13 14:44 UTC, merged